### ISSUE TITLE
normalize tag synonyms

### ISSUE THREAD

**Issue by jfirebaugh** [tj/dox#155]
JSDoc tag synonyms such as `@return` ([synonym for `@returns`](http://usejsdoc.org/tags-returns.html)) should be normalized to their canonical tag, so that downstream processors do not need to handle synonyms separately.

The synonym used can be preserved in an additional property of the tag object, e.g.:

```
* @return {String} escaped html
```

⇢

```
{
  "type": "returns",
  "synonym": "return",
  "types": [
    "String"
  ],
  "description": "escaped html"
}
```

**Comment by ChiperSoft** [comment]
Is there a list of all the synonyms somewhere?

**Comment by jfirebaugh** [comment]
Yes, they are listed on http://usejsdoc.org/ (search for "synonym").

**Comment by ChiperSoft** [comment]
I see a potential problem here if someone has already written code against dox that looks for `return` instead of `returns` because that's what their codebase has. For them, this would result in a BC break.

I'm unconvinced that dox should be doing that kind of normalization. Dox's job is to parse, not to interpret.

**Comment by jfirebaugh** [comment]
Yes, that's true, it would be a breaking change for some users.

I can live with this not being in dox, so I'll go ahead and close. Thanks for considering it!

**Comment by ChiperSoft** [comment]
Thanks for suggesting it.
